apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment1
  template:
    metadata:
      labels:
        app: assignment1
    spec:
      containers:
      - name: assignment1
        image: assignment1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
